# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ec407a67464fa555272f2c77b1e287022bc0ac3ccdc45a97750c00b4f4278c3ab7c7508b0bc27abc24a94247dc044f6e15dd3523844d85bc7ee33edbf9d7c59

test:
  secret_key_base: 891e4d1acca0a5148b8fe44b5bcc7172b67330fc94ab96914a990458f0271edd83874f4fd8cb57be079cdb85241c37bedce642b9feb12b5d7413a579fd198f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
